services:
  api:
    container_name: chatbot_api
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - DEFAULT_MODEL=gemma2:2b
      - SQLITE_PATH=/data/chat.db
    volumes:
      - api-data:/data
    depends_on:
      - ollama
    networks:
      - default

  ollama:
    container_name: ollama
    build: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama-models:/root/.ollama
    ports:
      - "11434:11434"
    entrypoint: ["/bin/bash", "-c", "/pull-models.sh"]
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  ollama-models:
    driver: local
  api-data:
    driver: local
