services:
  app_main:
    container_name: app_main
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - default

  ollama:
    container_name: ollama
    build: ollama
    volumes:
      - default-volume:/ollama
    networks:
      - default
    entrypoint: ["env/bin/activate.fish", "/pull-llama3.2:1b.sh"]

networks:
  default:
    driver: bridge

volumes:
  default-volume:
    driver: local
